 # docker-compose.yaml
version: '3.8'
services:
      jenkins:
          image: jenkins/jenkins:jdk11
          privileged: true
          user: root
          ports:
            - 8082:8080
            - 50000:50000
          container_name: jenkinsserver
          volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-home:/home
            - /var/run/docker.sock:/var/run/docker.sock
       
          
volumes:
  jenkins-data: {}
  jenkins-home: {}