 # docker-compose.yaml
version: '3.8'
services:
      jenkins:
          image: jenkins/jenkins:jdk11
          privileged: true
          user: root
          ports:
            - 8083:8080
            - 50000:50000
          container_name: jenkinsserver
          volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-home:/home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/bin/docker:/usr/local/bin/docker
        
          depends_on:
            - docker
      docker:
          image: docker:dind
          container_name: docker
          privileged: true
    
          volumes:
             - /var/lib/docker
          restart: always
          
volumes:
  jenkins-data: {}
  jenkins-home: {}