apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-maven
  labels:
    app: app-maven
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-maven
  template:
    metadata:
      labels:
        app: app-maven
    spec:
      containers:
      - name: newmavenappdevops
        image: mimi360/doc:docprod
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: app-maven
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 80